### ISSUE TITLE
Design System Integration and Storybook Setup

### ISSUE THREAD

**Issue by kneerose** [cardanoapi/drep-id#22]
#### TODO  
- [ ] Implement foundational styles (e.g., typography, colours, spacing) and reusable components (e.g., Button, Input) from the [design system](https://www.figma.com/design/n2fLSVUg6fFL4IgmMpMdJ8/Design-System---DRep---2024?node-id=2001-170&p=f&t=WbC8KOd4xPlyCLhh-0).  
- [ ] Install and configure Storybook in the Next.js project.  
- [ ] Create Storybook stories for foundational components (e.g., Button, Input) and modals, demonstrating their variations and usage.

**Comment by kneerose** [comment]
Different variations of the button component in storybook
![Image](https://github.com/user-attachments/assets/eadfb22b-abe6-423d-84c7-9d5d751f6a48)
![Image](https://github.com/user-attachments/assets/2b4d85dd-a0b1-4d01-900c-49f02a3dd9d7)

**Comment by kneerose** [comment]
Different variant of Badge
![Image](https://github.com/user-attachments/assets/af885d43-34cf-432d-a8a0-312e75e4dd91)
![Image](https://github.com/user-attachments/assets/bfc5146d-12b9-42a2-abdc-75b2278d8f45)

Different variant of inputfield
![Image](https://github.com/user-attachments/assets/3854a97b-3e1a-4d80-97a9-7dabda0b5124)
![Image](https://github.com/user-attachments/assets/8c99770e-e373-4caf-815d-a54c0d8e7636)

Different variant of text field
![Image](https://github.com/user-attachments/assets/683cb1a5-5a8c-4e78-8d57-311e84cd25ef)
![Image](https://github.com/user-attachments/assets/486cb3e8-0bc1-4a37-833a-cd3d877a4aec)

**Comment by kneerose** [comment]
Different variant of toast

![Image](https://github.com/user-attachments/assets/ef8d58c9-dfc9-4fe1-9f1a-e48795f1c68c)

![Image](https://github.com/user-attachments/assets/6568b4aa-9863-4f99-8958-47befbcf4017)

Profile DRopdown
![Image](https://github.com/user-attachments/assets/1f67acf2-73a6-4424-a973-5f2549768f46)
![Image](https://github.com/user-attachments/assets/15879314-d324-4a7a-9153-6cf7aa9662f5)
![Image](https://github.com/user-attachments/assets/89419f78-7615-4c3f-a105-91c8f2f5c1f2)

**Comment by kneerose** [comment]
### Wallet disconnect dialog 

**Dark Mode**
![Image](https://github.com/user-attachments/assets/38c0b66f-3cf0-431f-8409-dc2fdb85506c)

**Light Mode**
![Image](https://github.com/user-attachments/assets/aafe768d-f1b4-438f-a416-7025585ab394)

### Input field with pre and post-action

![Image](https://github.com/user-attachments/assets/17bba3be-edef-4d29-abd4-57b013d6f04a)

### Search Modal

**Dark Mode**

![Image](https://github.com/user-attachments/assets/cd1f5ee9-b954-49e7-b3fc-93de7b8b5560)
![Image](https://github.com/user-attachments/assets/3ac54d2b-ac8e-43ec-8e07-07ffe0fb53f5)
![Image](https://github.com/user-attachments/assets/db926add-aae4-40d8-b076-1e00fa077278)

**Light Mode**

![Image](https://github.com/user-attachments/assets/431320c1-bb89-4cf2-b0dc-a5c0e8ee2359)
![Image](https://github.com/user-attachments/assets/520a8034-be9d-49a9-8f58-02c4ceaa1ae2)
![Image](https://github.com/user-attachments/assets/4e20a7b5-20aa-4752-9573-570b0fb31c88)



### Design System implemented till now 
![Image](https://github.com/user-attachments/assets/9d16531b-0b6f-4a49-a9c0-a068a9c98af8)

**Comment by kneerose** [comment]
The current storybook is deployed at https://storybook-drep.sireto.dev/
- CD is remaining , need to update on script

**Comment by mesudip** [comment]
To review

**Comment by kneerose** [comment]
[#PR for design system and storybook setup](https://github.com/drep-id/drep.id/pull/40)

**Comment by kneerose** [comment]
- [Navbar component story](https://storybook-drep.sireto.dev/?path=/story/design-system-modals-navbar--default)

**Comment by kneerose** [comment]
- Created a [PR for Storybook deployment](https://github.com/drep-id/drep.id/pull/41).
