### ISSUE TITLE
update drep-id profile page according to new design

### ISSUE THREAD

**Issue by kneerose** [cardanoapi/drep-id#25]
figma link -> https://www.figma.com/design/kJW3ZOUarGHkipQlWzbDF1/DRep---Website?node-id=4065-21720&t=KaDAORp7FGk5YA8P-0

![Image](https://github.com/user-attachments/assets/4a55515b-4d0e-4ccb-bc37-39ffcb1f0eab)

### TODO
- [x] Implement the profile page design according to figma design
- [x] Add transaction in progress status for delegation and retire dRep
- [x] Implement empty tab content view
- [ ] Make profile page responsive

**Comment by kneerose** [comment]
![Image](https://github.com/user-attachments/assets/788c0956-3fd4-43df-8991-ea6fe3e5b077)
![Image](https://github.com/user-attachments/assets/6b1b7a94-5667-4938-8569-8509f4d2be64)
![Image](https://github.com/user-attachments/assets/b4007051-a5c6-47a5-994f-3592b6f75183)
![Image](https://github.com/user-attachments/assets/076a09fd-375c-4183-bce3-38951c87ba07)

**Comment by kneerose** [comment]
- DRep with no other metadata than social links
![Image](https://github.com/user-attachments/assets/37e9d3ce-d9b3-4411-859d-d901b9b8691b)
- Transaction in progress for delegate and retire as a dRep
![Image](https://github.com/user-attachments/assets/306acc3e-87e4-48c9-b54a-4de5083ebc0f)

- Retire as a dRep modal
![Image](https://github.com/user-attachments/assets/d98b7ead-6e9b-40ed-a662-c235c129f9b7)

**Comment by mesudip** [comment]
Responsive design will be covered in different ticket
